copy

diff --git a/.github/workflows/04-deploy copy.yaml b/.github/workflows/04-deploy copy.yaml
--- a/.github/workflows/04-deploy copy.yaml
+++ b/.github/workflows/04-deploy copy.yaml
@@ -1,12 +1,12 @@
-name: 04 Deploy Workflow
+name: 04 Deploy Workflow Copy
 
 on:
   workflow_dispatch:
 
 env:
-  IMAGE_NAME: tiny-health-container-vars
-  CONTAINER_NAME: tiny-health-container-vars    
   BASE_IMAGE: python:3.12-slim
+  IMAGE_NAME: tiny-health-app
+  CONTAINER_NAME: tiny-health-container
   APP_PORT: 8000
 
 jobs:
@@ -14,36 +14,58 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Build Docker image
+      - name: Create .env file
+        run: |
+          echo "APP_ENV=production" >> .env
+          echo "PORT=${APP_PORT}" >> .env
+
+      - name: Build Docker image (dynamic base)
         run: |
           docker build \
-            --build-arg BASE_IMAGE=${{ env.BASE_IMAGE }} \
-            -t ${{ env.IMAGE_NAME }} .
+            -f Dockerfile.prod \
+            --build-arg BASE_IMAGE=${BASE_IMAGE} \
+            --build-arg APP_ENV=production \
+            --build-arg APP_PORT=${APP_PORT} \
+            -t ${IMAGE_NAME}:latest \
+            .
 
       - name: Run container
         run: |
           docker run -d \
-            -p 8000:8000 \
-            --name ${{ env.CONTAINER_NAME }} \
-            ${{ env.IMAGE_NAME }}
-      - name: Check running containers
-        run: docker ps
+            --name ${CONTAINER_NAME} \
+            --env-file .env \
+            -p ${APP_PORT}:${APP_PORT} \
+            ${IMAGE_NAME}:latest
 
-      - name: Smoke test deployed app
+      - name: Check container is running
         run: |
-          for attempt in 1 2 3 4 5; do
-            if curl --fail --silent http://127.0.0.1:8000/health; then
-              exit 0
-            fi
-            echo "Waiting for app to become ready..."
-            sleep 2
-          done
-          echo "App did not become ready in time."
-          exit 1
+          docker ps
 
-      - name: Stop container
+          if [ "$(docker ps -q -f name=${CONTAINER_NAME})" ]; then
+            echo "Container is running "
+          else
+            echo "Container is NOT running "
+            docker logs ${CONTAINER_NAME}
+            exit 1
+          fi
+
+      # - name: Smoke test deployed app
+      #   # Retry a few times because app startup can take a moment.
+      #   run: |
+      #     for attempt in {1..10}; do
+      #       if curl --fail --silent http://127.0.0.1:8000/health; then
+      #         exit 0
+      #       fi
+      #       echo "Waiting for app to become ready..."
+      #       sleep 2
+      #     done
+      #     echo "App did not become ready in time."
+      #     exit 1
+
+
+      - name: Cleanup
         if: always()
-        run: docker rm -f ${{ env.CONTAINER_NAME }} || true
+        run: docker rm -f ${CONTAINER_NAME} || true
